name: Deploy to Render

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RENDER_API_KEY: ${{ secrets.RENDER_DEPLOY_KEY }}

    steps:
    - name: Trigger Render deployment
      run: curl -X POST https://api.render.com/deploy/srv-cniutm0l6cac739b1t30?key=$RENDER_API_KEY
