name: Deploy to Render

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RENDER_API_KEY: ${{ secrets.RENDER_DEPLOY_KEY }}

    steps:
    - name: Trigger Render deployment
      run: |
        set -e
        response=$(curl -s -X POST https://api.render.com/deploy/srv-cniutm0l6cac739b1t30?key=$RENDER_API_KEY)
        if [ $? -ne 0 ]; then
          echo "Error deploying to Render"
          echo "$response"
        fi
